<a href="https://colab.research.google.com/github/mateo-me/Colab/blob/main/Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

def buscar_pivo(L):
    p = np.nonzero(L)[1]
    if p.size:
        return p[0]
    return L.size

mat = np.matrix([[1,  0,  0,  0],
                 [0,  1,  0,  0],
                 [1,  0,  5,  0],
                 [2,  1,  1,  0],]).astype(float)

res = mat[np.argsort(np.apply_along_axis(buscar_pivo, axis=1, arr=mat))]
print(res)

[[1. 0. 0. 0.]
 [1. 0. 5. 0.]
 [2. 1. 1. 0.]
 [0. 1. 0. 0.]]
